apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: prometheus
spec:
  selector:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Choose a port between 30000-32767
  type: NodePort

