apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server-pv
spec:
  capacity:
    storage: 5Gi  # Adjust size according to your needs
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /mnt/flaskapp-storage-class-Prometheus-PV/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker1

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alertmanager-pv  # Lowercase and no uppercase letters
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /mnt/flaskapp-storage-class-alertmanager/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker1
  claimRef:
    namespace: prometheus
    name: storage-prometheus-alertmanager-0
