apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-exporter
  namespace: prometheus
spec:
  selector:
    matchLabels:
      app: mysql-exporter
  endpoints:
    - port: "metrics"  # Ensure this is a string
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
    - default

