# Prometheus server configuration
server:
  retention: 15d
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  nodeSelector:
    "kubernetes.io/os": linux
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
  persistentVolume:
    enabled: true
    size: 5Gi
    storageClass: "local-storage"
  service:
    type: LoadBalancer  # Use LoadBalancer to align with your existing setup

# Alertmanager configuration
alertmanager:
  enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  nodeSelector:
    "kubernetes.io/os": linux
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
  persistentVolume:
    enabled: true
    size: 3Gi
    storageClass: "local-storage"
  service:
    type: LoadBalancer  # Use LoadBalancer to align with your existing setup

# Node Exporter configuration
nodeExporter:
  enabled: true
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  nodeSelector:
    "kubernetes.io/os": linux
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
