apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-tier-app
  labels:
    app: two-tier-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two-tier-app
  template:
    metadata:
      labels:
        app: two-tier-app
    spec:
      containers:
      - name: two-tier-app-pod
        image: ali0322/flaskapp:latest
        env:
        - name: MYSQL_HOST
          value: "10.98.2.37"  # Ensure this matches your MySQL service IP
        - name: MYSQL_PASSWORD
          value: "admin"
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_DB
          value: "mydb"
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
