apiVersion: v1
kind: PersistentVolume
metadata:
  name: flaskapp-data-pv
#  labels:
#    type: local
spec:
  hostPath:
# At below line, Specify the path on the host machine(on db-pod)  where the volume will be mounted
#    path: "/home/admin1/mysql-pv-moutpoint" 
    path: /mnt/flaskapp-data-pv
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flaskapp-data-pvc
spec:
  resources:
    requests:
      storage: 50Mi
  accessModes:
    - ReadWriteMany

